name: sendMessage

on:
  schedule:
    - cron: '0 1 * * *' # 北京时间上午9
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Run Project
        run: npm install && npm run serve
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
          CITY: ${{ secrets.CITY }}
          CITY_CODE: ${{ secrets.CITY_CODE }}
          HF_KEY: ${{ secrets.HF_KEY }}
          MEET_DAY: ${{ secrets.MEET_DAY }}
